### ISSUE TITLE
manage.py is broken

### ISSUE THREAD

**Issue by SteveGZr** [wfehr/django-time-wizard#3]
The manage.py in your repo is broken. 
The following line does not work:
`    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "test/settings")`

The directory is `tests` not `test` and you need to have a python module there. So the following would be correct:
`    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tests.settings")`

**Comment by wfehr** [comment]
Fixed with 10dee9cee878050e297b65337f4f675ace71aaed
